### ISSUE TITLE
Documentation Update on Scanner Configuration

### ISSUE THREAD

**Issue by ratzrattillo** [v-p-b/oracle_forms#10]
I believe it might be helpful to update the Readme with a section on how to set up the scanner correctly when working with this plugin. This could include:

- Scanning with only a single thread
- Activating/Deactivating specific Burp insertion points that break the protocol
- Selection of issues that do make sense to be scanned for
- Export an example Scan Configuration to make it available for importing in Burps Configuration library
- Give a hint, that the insertion points are listed in the plugin output.

What do you think? I believe this would benefit usability and adoption of the plugin, aswell as less questions and issues here on GitHub.
Keep up the good work!

**Comment by v-p-b** [comment]
Interesting idea! I'm afraid that the main issue is usually not the Scanner config, but session handling/macros, that can be strongly target specific. I really like the idea of sharing Scanner configs (more projects should do this actually!), but I'm afraid, that people will just load it up and fire on their target, without considering the problems of statefulness.

I agree that the README should at least include some summary about the caveats of the configuration and probably a link to the Hacktivity talk too, so I keep this on my list. Meanwhile, if you have any thoughts regarding my previous concerns, don't hesitate to share!

**Comment by v-p-b** [comment]
I think ae1f5d985a481000f8fcafd9daa369ef555870d2 fixes this.
