### ISSUE TITLE
java.lang.NoClassDefFoundError: oracle/forms/engine/Message

### ISSUE THREAD

**Issue by 0x25** [v-p-b/oracle_forms#12]
Hello, for sharing

**Action done :**  
1. import "OracleFormsSerializer" in Eclipse (add frmall.jar in /lib manually - import project folder to Eclipse - Export project to JAR from eclipse)  
2. Add extension in Burp without import error  

**Error :** 
Run the applet in browser.  
Get the "java.lang.NoClassDefFoundError: oracle/forms/engine/Message" in extentions errors when accessing the "Oracle form" tab in Burp Proxy Request/Response.   

**To do/solution:**
Configure Tab Extender > Options > Java Environnement  
Create a path and add frmall.jar in it.  

**Ref:**
https://forum.portswigger.net/thread/loading-external-jars-from-extensions-0e37252c  
https://portswigger.net/burp/documentation/desktop/tools/extender#options_javaenv

**Comment by v-p-b** [comment]
As described in https://github.com/v-p-b/oracle_forms/commit/8dcb4c8debd250edbf44d1219325aa4f18219ca7 .
