### ISSUE TITLE
see response messages, but they are not deserialized

### ISSUE THREAD

**Issue by dbulloch** [v-p-b/oracle_forms#14]
Question - does it matter what version of Burp we're using?  How about what version of Java?

I grabbed frmall.jar from app and copied to the lib directory before building the OracleFormsSerializer.jar. I also set the Java Environment in Burp Extender Options tab to point to the lib folder.

Extension loads without errors.

Running the mitmdump command with the mitmproxy_oracleforms.py also runs without errors and Burp is configured to use this for Upstream Proxy Servers (and I can see successful communications in the mitmdump console when using the web app).

However, when I go to forms-demo.com, I do see the requests and response in Burp, but all the responses with parameters are still encrypted and unreadable. I don't get an Oracle Forms tab in my Proxy page, instead I see an Extension dropdown were I can pick Oracle Forms ... but when I select it, I get a blank response (which seems similar to issue #10 that was closed).

I am using Burp Suite Professional v2020.11 and Java 1.8.0_181

Any help greatly appreciated.

**Comment by v-p-b** [comment]
The Message Viewers changed just recently in Burp and I haven't tested the extension with the latest Burp. 

Note that the extension only cares about String parameters, no requests and responses don't necessarily result in an output. 

There is usually a initialization message sent after the initial handshake. If the decryption is working you should see something similar to the screenshot shown in this presentation around 20:47:

https://www.youtube.com/watch?v=hEoeDPk4TOE

This is a good way to check whether the crypto stuff works in the first place. If you can see readable strings the MessageViewer should be able translate to HTTP queries.

**Comment by v-p-b** [comment]
I just tested the latest Burp, and it works as expected: 
![screen1605967411](https://user-images.githubusercontent.com/540246/99879227-af2a9d00-2c0b-11eb-9220-1ef532c84781.png)

I also created a video about setting up the extension:

https://vimeo.com/482011043

**Comment by v-p-b** [comment]
Do you have any update on this?

**Comment by dbulloch** [comment]
I replicated every step in the video and the payload was still always encrypted (and selecting the Oracle Forms extension always displayed a blank).

I'm not sure why it doesn't work for me.

**Comment by v-p-b** [comment]
If decryption is not happening, then something is wrong at the mitmproxy part, not the Burp Extension. Do you see the following message in the mitmproxy output: `RC4 initialized with key:...` ?

**Comment by dbulloch** [comment]
I agree that something isn't working for me with mitmproxy, but I'm using the exact same file and command that you are

![image](https://user-images.githubusercontent.com/613178/101067899-ecb4f180-354c-11eb-826b-d8cad334d088.png)

**Comment by v-p-b** [comment]
The error message is right there: you don't have Python Requests installed:

`pip install requests`
