### ISSUE TITLE
[!] Invalid request message

### ISSUE THREAD

**Issue by 0x25** [v-p-b/oracle_forms#17]
Hello
Is it possible to have explanations about :

```
            if not flow.request.content.endswith(b"\xf0\x01"):
                ctx.log("[!] Invalid request message?")
```

I test an app and the script (mitm) catch well the key but after I get this warning. Of course the end of the packet is f001 :) (no bug)

Thanks

**Comment by v-p-b** [comment]
Can you modify the script to dump `repr(flow.request.content)` somewhere so we can see why this condition doesn't match?

**Comment by 0x25** [comment]
Sorry I don't have no more time on my test :/ But my interrest was on why you add this test. If you don't have time to explain you can just close or delete this topic.

**Comment by v-p-b** [comment]
This is just a basic sanity check, nothing critical. If it causes problems it can be removed.
