### ISSUE TITLE
Illegal close Message detected when using the extension

### ISSUE THREAD

**Issue by WaiZ0** [v-p-b/oracle_forms#19]
**Describe the bug**
Hi, I'm trying to use the too, but I'm getting an error from an illegal close.

**To Reproduce**
I compiled the OracleFormsSerializer.jar with my frmall.jar of my oracles form application then did the setup on the readme (

**Expected behavior**
I should be able to see some clear text from the request and response.

**Screenshots**
Extension output:
![image](https://user-images.githubusercontent.com/33723878/149160439-f0081119-f910-40df-98e4-e45caa50aed4.png)

Upstream proxy:
![image](https://user-images.githubusercontent.com/33723878/149161567-03cf16af-8d09-49ca-8a99-d00c14fa84b5.png)

Mitmproxy output:
![image](https://user-images.githubusercontent.com/33723878/149160882-e3cd0b30-9841-4c99-b0ed-499e43173287.png)

Here is a request from the login sequence if it can help:
![image](https://user-images.githubusercontent.com/33723878/149161114-fd033475-9772-4c7c-807c-051e2ca2b4de.png)

And the response with the oracle forms view is just empty.

As seen in the code here is the response with HEX format and there is no 0xf0 bytes (info from source code BurpExtender.java):
![image](https://user-images.githubusercontent.com/33723878/149162029-9ff9d51f-9b53-4eef-ad44-5f50c5e86a11.png)

I dont really know where the problem comme from, may it be possible that there is a different encyrption used or anything like that ?

Thanks for your help

**Comment by v-p-b** [comment]
It seems that you are not intercepting the key exchange ("GDay" and "Mate" messages). You should see messages like this in the mitmdump output:

https://github.com/v-p-b/oracle_forms/blob/master/mitmproxy_oracleforms.py#L143

I wouldn't rule out that Oracle changed something - can you share the exact Forms version you are targeting?

Also, you can test your setup on forms-demo.com to verify if everything is set up correctly as shown here:

https://vimeo.com/482011043

**Comment by WaiZ0** [comment]
Hi,

Thank you for you anwser. Indeed the key exchange was not working because of a too recent version of mitmproxy. I installed version 4.0.4 on my linux host (lot easier that windows) then it worked (https://github.com/v-p-b/oracle_forms/issues/13).

Now the Oracle Forms view is working in Burp ! 

Also last thing, about the testing Oracle forms: as you mentioned the [forms-demo.com](https://forms-demo.com/plsql/cd_forms12demo?sg=0&anw=1) links to easily do some tests are not available anymore (only screenshot and sources).

**Comment by v-p-b** [comment]
Glad this is resolved! 

Also, thanks for the heads up about the demo site, this is very unfortunate :(
