### ISSUE TITLE
Unable to view the output values in Burp Pro

### ISSUE THREAD

**Issue by avaradan** [v-p-b/oracle_forms#2]
Hi ,
I downloaded and setup the FormsTester Extension on Burp suite pro version but I can't see the values that gets transmitted. I rather see the applet controls with x,y positions as you can see below. Am I missing something?

```
Response:
Encrypted Response: 
Body: 0 byte(s)
Request:
Encrypted Request: 5bb1de6102076f2bca421a4a48d2b4fa9a7997caf58594c0ed43202b7011feed605db2
6458813180627c48bb36d024509e7d3fee6d0a275430223eb6d1184ae696c6cf
Body: 35 byte(s)
Property 0: 195 Type: 9
--- Value: java.awt.Point[x=0,y=3]
Property 1: 193 Type: 3
--- Value: 3
Message OK
Property 0: 135 Type: 9
--- Value: java.awt.Point[x=0,y=0]
Message OK
Property 0: 137 Type: 9
--- Value: java.awt.Point[x=1280,y=1024]
Message OK
100216a0c30000000320c103f0100006a08700000000f0100006a08905000400f0f001

---
Response:
Encrypted Response: 
Body: 0 byte(s)
Request:
Encrypted Request: 
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Body: 0 byte(s)
Request:
Encrypted Request: 
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Body: 0 byte(s)
Request:
Encrypted Request: 
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Body: 0 byte(s)
```

Thanks
Aravindan

**Comment by v-p-b** [comment]
The debug output seems OK: The displayed Point objects suggest that the extension can correctly decrypt and parse messages.

Oracle Forms keeps track of the state of the UI at server side by default, so you won't see messages similar to standard HTTP (e.g. "The button with name X and value Y got clicked") instead the framework only sends coordinates (Point objects) and the server will figure out what UI element was at that coordinate. 

Try changing text field values, then you should see the new String values transmitted.
