### ISSUE TITLE
Problem deserializing

### ISSUE THREAD

**Issue by andreashappe** [v-p-b/oracle_forms#3]
Hi,
I've created the BURP Extension and starting it with Burp Suite Pro 1.7.03. I cannot decipher any packets, output in extender view starts with:

```
Body: 0 byte(s)
Request:
Encrypted Request: 4e554c4c504f5354
12bc43d84b338c6bcb693509cce52df6d271dd178d9bd5caa3497936883bf961
Body: 8 byte(s)
Message IOException
java.io.EOFException
    at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
    at oracle.forms.engine.Message.readDetails(Unknown Source)
    at burp.BurpExtender.processProxyMessage(BurpExtender.java:131)
    at burp.lyb.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
0ccf49dd8c21c8ad
```

Also I do only have the "Oracle Forms"-Tab on requests, not on incoming responses. I did the "exchange line 199"-Bugfix from issue #1  (otherwise it wouldn't decode too much).

I also have the problem (when looking into the debug log) that some types are not serialized:

```
Encrypted Response: 2b18a35b61aaca8a4236dbeeba9f2ce359a5d9450389a5d4d42054a312aa588604272629648414e2b6c4239d402e0941b0a50492ab54308b425722b025cbb54234e85136c0f84d82968777069d3b34703f5c0081ade6fe6b43a2744a9bb28fc661c5f87845dd18bb582346809a38f05d58e24387536a70adc5773a1084fecf088738ea7d7b68376396259d7154ff9454fd37de527e01add26daf6fbe2e5f8dcb2d9a91c56ecd95be6551c82f4b9844d2c3c76380a6e1799f35212ef59fd32534265a8416272daa502e2bcb140f783cdb548bdd6f89af22fc577d10afc176589f280fc63756360347272d5ae2101ba0529eb34874fcf48a3bbcc661457b42567a4562aadd8022ecdb57c8c2a0
Body: 268 byte(s)
Message IllegalArgumentException
java.lang.IllegalArgumentException: Attempt to read in an object of type 104
        at oracle.forms.engine.Message.readDetails(Unknown Source)
        at burp.BurpExtender.processProxyMessage(BurpExtender.java:131)
        at burp.lyb.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

should I include additional jar files? I've manually added the mentioned jar file -- this application is partly written in German, could that have some impact?

cheers, Andreas

**Comment by nv1t** [comment]
Have you found any workaround? I'm having the same issue. (also German application)

**Comment by andreashappe** [comment]
not really :-/

**Comment by v-p-b** [comment]
- Please don't post multiple problems under the same issue!
- Please give descriptive titles! Deserialization is probably the only thing that will ever fail, so "Problem deserializing" doesn't give away much clue for users who browse the tracker.

In the first case you clearly try to deserialize a 0 bytes long stream (first line in the output, the Encrypted Request is "NULLPOST" in hex), thus the EOF exception.
