### ISSUE TITLE
Use with socket applet configuration

### ISSUE THREAD

**Issue by dhuyp** [v-p-b/oracle_forms#8]
Hello,

Will it be possible to make this tool available for socket connection?

**Comment by v-p-b** [comment]
Sorry, but no. Proxying TCP traffic is a huge PITA.

**Comment by dhuyp** [comment]
Just to be sure, it's still the mechanism for modern implementation?

**Comment by v-p-b** [comment]
Last time I checked it worked against https://forms-demo.com/, that is based on 12c.
