### ISSUE TITLE
Update Description how to load plugin

### ISSUE THREAD

**Issue by ratzrattillo** [v-p-b/oracle_forms#9]
In the description it says, that in order to successfully use the plugins, the CLASSPATH has to be adjusted:

> To use these programs include frmall.jar archive provided by Oracle Forms in your classpath.

This is not working with BurpSuite 2020.2.1. The folder with the fmrall.jar must be added to the JAVA Environment in the BurpSuite Extender Options. Otherwise a Stacktrace will occur, that the oracle/forms/engine/Message class cannot be found during runtime, even if it has been included in the BuildPath in Eclipse for the .jar file of the OracleFormsSerializer Extension.

Maybe this hint could be supplied in the description on how to use the plugin!

**Comment by v-p-b** [comment]
Thanks for the report! I updated the README.
